---
log:
  stdout_log_level: INFO
  log_file_level: INFO
  log_file: solace_ai_connector.log

shared_config:
  - broker_config: &broker_connection
      broker_connection_share: ${SOLACE_BROKER_URL}
      dev_mode: ${SOLACE_DEV_MODE, false}
      broker_url: ${SOLACE_BROKER_URL}
      broker_username: ${SOLACE_BROKER_USERNAME}
      broker_password: ${SOLACE_BROKER_PASSWORD}
      broker_vpn: ${SOLACE_BROKER_VPN}
      temporary_queue: ${USE_TEMPORARY_QUEUES, false}

  - web_ui_config: &web_ui_config
      enabled: true
      listen_port: 5001
      host: 0.0.0.0
      response_api_url: http://20.127.157.178:5050/api/v1/request
      frontend_url: http://20.127.157.178:5001
      frontend_server_url: http://20.127.157.178:5001
      # CORS settings for remote access
      cors_origins: ["*"]
      cors_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      cors_headers: ["Content-Type", "Authorization", "X-Requested-With"]

flows:
  # Web UI with CORS support
  - name: web_ui
    trace_level: ERROR
    components:
      - component_name: web_ui
        component_module: solace_ai_connector_web.backend.server
        component_config:
          <<: *web_ui_config 